### ISSUE TITLE
Make the generator escape description strings

### ISSUE THREAD

**Issue by ngottlieb** [lsetiawan/rppc#11]
Rppc doesn't escape single quotes in the `description` field which causes all kinds of problems in the generated `setup.py`. You probably want to do a bit more escaping than just for quotes as well -- it's just a description string and you want to be sure it stays that.

**Comment by ngottlieb** [comment]
Just glanced at the code -- solving this should probably involve escaping / validating all the input values, not just description.

**Comment by lsetiawan** [comment]
Thanks @ngottlieb for opening an issue for this. :smiley:

**Comment by ngottlieb** [comment]
Hahah no worries! Figured you wouldn't want to forget about it!
